/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import org.junit.Test;

import java.lang.reflect.Array;

import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }

    @Test public void testShiftArray(){
        int [] inputArr = new int[]{1,2,3};
        int [] expected = new int[]{1, 2, 9, 3};
        int [] actual = Library.arrayShift(inputArr, 9);
        assertArrayEquals(expected, actual);
    }
}
