/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package challenges;
import java.lang.*;
import java.util.Arrays;



public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }

    public static int[] arrayShift(int [] args, int num){

       return mid(args, num);
    }

    public static int[] mid(int [] arr, int num) {
        int len = (arr.length + 1);
        int[] newArr = new int[len];
        int index = 0;
        int middle = (int) Math.ceil(((arr.length + 1) / 2));
        for (int i = 0; i < arr.length; i++) {
            System.out.println(arr[i]);
            if (index == middle) {
                newArr[middle] = num;
                index = middle + 1;
                i = i - 1;
            } else if (index != middle) {
                newArr[index] = arr[i];
                index++;
            }
        }
        return newArr;
    }
}
